[shell]
clipboard_auto_paste = "off"
polkit_agent = true

    [shell.animation]
    enabled = false

    [shell.launcher]
    categories = false
    compact = true

        [shell.launcher.providers.emoji]
        global = false

    [shell.panel]
    clipboard_placement = "attached"
    launcher_placement = "attached"

    [shell.screen_corners]
    enabled = true

    [shell.screenshot]
    confirm_region = true
    directory = "/home/alvin/Pictures/Screenshots"

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 0.0
    enabled = true
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 10.0
    enabled = true
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 10.0
    enabled = true
    variant = "destructive"
